name: ImageProcessingAtom

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B "${{ github.workspace }}/build" -S "${{ github.workspace }}" -DCMAKE_CXX_FLAGS="/MP"

      - name: Build Target
        run: |
          cmake --build "${{ github.workspace }}/build" --target ImageProcessingAtom.Editor --config Release --parallel
