name: Build ImageProcessingAtom.Editor

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build Target
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'

      - name: Configure project
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build target
        run: cmake --build build --config Release --target ImageProcessingAtom.Editor
